### PR TITLE
Create minting-a-new-native-asset-en.md

### PR DESCRIPTION
**Pull request by fsancheziohk**
Adding new file explaining how to create a new native asset.

## What? (required)

New file 'minting-a-new-native-asset.

### CODE REVIEW

**Review by kevinhammond — COMMENTED** [review]
Generally be careful with  using specific build numbers in wget.  Here, you should be OK unless the configuration information or node changes later...

**Review by kevinhammond — CHANGES_REQUESTED** [review]
Clarify that this is for Linux/x86/bash

**Review by kevinhammond — COMMENTED** [review]
port 3001 may be hazardous if already running a mainnet relay

**Review by kevinhammond — CHANGES_REQUESTED** [review]
Be consistent with the use of '$'  Either use it before all commands, or before no command.

**Comment by kevinhammond** [comment]
There are several points where you're using specific values that have been obtained (eg policy id, UTxO address).  At a minimum, state this in each case.  Ideally, do what Philipp and I have done (save results in variables and use these).  You should describe this as a worked example rather than a script unless you do make it abstract where necessary.

**Comment by kevinhammond** [comment]
I don't have write access to approve this, of course

**Review by fsancheziohk — COMMENTED** [review]
Changes reviewed & thank you

**Review by jonnysmillie — CHANGES_REQUESTED** [review]
This file needs to have to requisite YAML frontmatter in order to place it in the appropriate place in the website. Please see the other files and let me know if you need guidance.

**Comment by fsancheziohk** [comment]
Closing PR

**Pull request closed without merging**
