### PR TITLE
Update 2020-05-05_16-12-19_installing-and-running-the-cardano-node-en.md

### LINKED ISSUE #400: Invalid content /en/testnets/cardano/get-started/installing-and-running-the-cardano-node/
**Where does the issue occur?**
Dead links here

**Describe the issue**
Dead links here

**Expected changes**
Proper links

### PR DESCRIPTION
**Pull request by olgahryniuk**
Fixing a link to 'supported platforms', resolves #400

### CODE REVIEW

**Comment by olgahryniuk** [comment]
also fixes #399

**Comment by olgahryniuk** [comment]
fixes #398

**Comment by olgahryniuk** [comment]
Also fixes #395

**Review by nahern — APPROVED** [review]
approved changes

**Pull request merged**
